DB_HOST = '127.0.0.1'
DB_PORT = 3306
DB_DBNAME = "observium"
DB_USER = "root"
DB_PASSWORD = "mypwd"

DB_MIN_CACHED = 10
DB_MAX_CACHED = 30
DB_MAX_SHARED = 0
DB_MAX_CONNECYIONS = 50
DB_CHARSET = "utf8"
